# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b10c735450b1db6dd4963f71a1663ebc93b23e9e47c35db04405402110e50f01edf0a4390b1aa7a12d908867832b01d7f3313448cb601f65e28d2877c53b0d28

test:
  secret_key_base: 5bdb82a5997de1328542480a22f322b6c44b7a4509ef5335deeda22014f6ff81339f79249484e16c97676c63bd46bc5d9c5b6c32b29f5500bd609c1af56b6495

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
